export const products = [
  {
    id: "buy-alluvi-retatrutide-40mg-x2-bundle",
    name: "Alluvi Retatrutide 40mg ×2 Bundle",
    slug: "buy-alluvi-retatrutide-40mg-x2-bundle",
    tag: "ALLUVI",
    description: "Alluvi Retatrutide 40mg ×2 Bundle includes two pre-calibrated research devices designed for precision, consistency, and extended laboratory use. Ready-to-use with no preparation required, making it ideal for high-volume and multi-phase research workflows.",
    priceFrom: 204.75,
    variants: [{"id":"var_0","name":"1 Item","price":204.75,"savingsLabel":""}],
    image: "https://peptidelabuk.co.uk/wp-content/uploads/2026/04/Retatrutide-40mg-RD-Only-X-2.png",
    thumbnails: []
  },
  {
    id: "buy-alluvi-retatrutide-20mg-pen",
    name: "Alluvi Retatrutide 20mg (R&D)",
    slug: "buy-alluvi-retatrutide-20mg-pen",
    tag: "ALLUVI",
    description: "Alluvi Retatrutide 20mg is a pre-calibrated research device designed for precision and convenience in laboratory settings. Ready-to-use with no preparation required, ensuring consistent and efficient experimental use. Approved for human use.",
    priceFrom: 65,
    variants: [{"id":"var_0","name":"1 Item","price":65,"savingsLabel":""}],
    image: "https://peptidelabuk.co.uk/wp-content/uploads/2026/04/68c153351d1a646053b66e98_Retatrutide-5MG-With-Pen-1-scaled.jpg",
    thumbnails: []
  },
  {
    id: "alluvi-retatrutide-bpc-157-tb-500-40mg",
    name: "Alluvi Retatrutide BPC-157 & TB-500 40mg",
    slug: "alluvi-retatrutide-bpc-157-tb-500-40mg",
    tag: "ALLUVI",
    description: "Alluvi Retatrutide BPC-157 & TB-500 40mg is a ready-to-use research pen combining three advanced peptides in a pre-measured laboratory formulation. Designed strictly for research purposes, this prefilled device offers precision handling, consistency, and convenience for controlled experimental settings across the UK and Europe.",
    priceFrom: 90.99,
    variants: [{"id":"var_0","name":"1 Item","price":90.99,"savingsLabel":""}],
    image: "https://peptidelabuk.co.uk/wp-content/uploads/2026/02/Alluvi-Retatrutide-BPC-157-TB-500.png",
    thumbnails: []
  },
  {
    id: "alluvi-glow-ghk-cu-bpc-157-tb-500-70mg",
    name: "Alluvi Glow GHK-Cu – BPC-157 & TB-500 70mg",
    slug: "alluvi-glow-ghk-cu-bpc-157-tb-500-70mg",
    tag: "ALLUVI",
    description: "Alluvi Glow GHK-Cu – BPC-157 & TB-500 70mg is a pre-calibrated research peptide blend developed for laboratory and in-vitro research purposes only. This advanced 70mg research formula combines three widely studied peptides in a ready-made research device, manufactured to high analytical standards and supplied exclusively for R&D use within the UK and Europe.",
    priceFrom: 58.49,
    variants: [{"id":"var_0","name":"1 Item","price":58.49,"savingsLabel":""}],
    image: "https://peptidelabuk.co.uk/wp-content/uploads/2026/02/Alluvi-Glow-GHK-Cu-–-BPC-157-TB-500-70mg.png",
    thumbnails: []
  },
  {
    id: "alluvi-nad-1000mg",
    name: "Alluvi NAD+ 1000mg",
    slug: "alluvi-nad-1000mg",
    tag: "ALLUVI",
    description: "Alluvi NAD+ 1000mg is a high-purity research compound supplied in a pre-calibrated research format for laboratory and in-vitro use only. Designed for controlled scientific investigation, this premium 1000mg NAD+ formulation is available across the UK and Europe exclusively for R&D purposes.",
    priceFrom: 110.49,
    variants: [{"id":"var_0","name":"1 Item","price":110.49,"savingsLabel":""}],
    image: "https://peptidelabuk.co.uk/wp-content/uploads/2026/02/Alluvi-NAD-1000mg.png",
    thumbnails: []
  },
  {
    id: "alluvi-tirzepatide-40mg",
    name: "Alluvi Tirzepatide 40mg",
    slug: "alluvi-tirzepatide-40mg",
    tag: "ALLUVI",
    description: "Alluvi Tirzepatide 40mg R&D Only is a high-purity, pre-calibrated research pen designed exclusively for laboratory and analytical research applications. Manufactured to strict quality standards and distributed across the UK and Europe, this ready-to-use research device ensures precision handling, consistency, and controlled laboratory study use. For research purposes only.",
    priceFrom: 77.99,
    variants: [{"id":"var_0","name":"1 Item","price":77.99,"savingsLabel":""}],
    image: "https://peptidelabuk.co.uk/wp-content/uploads/2026/02/Alluvi-Tirzepatide-40mg.png",
    thumbnails: []
  },
  {
    id: "alluvi-retatrutide-40mg",
    name: "Alluvi Retatrutide 40mg",
    slug: "alluvi-retatrutide-40mg",
    tag: "ALLUVI",
    description: "Alluvi Retatrutide 40mg R&D Only is a high-purity, pre-calibrated research pen designed exclusively for laboratory and analytical research applications. Supplied across the UK and Europe, this ready-to-use research device ensures precision handling, structured laboratory testing, and reliable research consistency. For laboratory research use only.",
    priceFrom: 123.49,
    variants: [{"id":"var_0","name":"1 Item","price":123.49,"savingsLabel":""}],
    image: "https://peptidelabuk.co.uk/wp-content/uploads/2026/02/Retatrutide-40mg-RD-Only-alluvii-1536x1026-1.png",
    thumbnails: []
  },
  {
    id: "alluvi-tirzepatide-20mg",
    name: "Alluvi Tirzepatide 20mg",
    slug: "alluvi-tirzepatide-20mg",
    tag: "ALLUVI",
    description: "Alluvi Tirzepatide 20mg R&D Only is a high-purity, pre-calibrated research pen designed exclusively for laboratory and analytical research use. Supplied across the UK and Europe, this ready-made research device ensures precision handling, structured testing, and consistent batch performance. For research purposes only.",
    priceFrom: 51.99,
    variants: [{"id":"var_0","name":"1 Item","price":51.99,"savingsLabel":""}],
    image: "https://peptidelabuk.co.uk/wp-content/uploads/2026/02/Alluvi-Tirzepatide-20mg.png",
    thumbnails: []
  },
  {
    id: "alluvi-retatrutide-20mg-x2-bundle",
    name: "Alluvi Retatrutide 20mg ×2 Bundle",
    slug: "alluvi-retatrutide-20mg-x2-bundle",
    tag: "ALLUVI",
    description: "Alluvi Retatrutide 20mg ×2 Bundle provides two pre-calibrated 20mg research pens designed exclusively for laboratory and analytical research use. Ideal for structured testing and extended research protocols, this bundle ensures batch consistency, secure packaging, and UK & EU supply. For research purposes only.",
    priceFrom: 129.99,
    variants: [{"id":"var_0","name":"1 Item","price":129.99,"savingsLabel":""}],
    image: "https://peptidelabuk.co.uk/wp-content/uploads/2026/02/Alluvi-Retatrutide-20mg-×2-Bundle.png",
    thumbnails: []
  },
  {
    id: "tirzepatide-10mg",
    name: "Tirzepatide 10mg",
    slug: "tirzepatide-10mg",
    tag: "PEPTIDE",
    description: "Each vial contains 10mg of highly pure Tirzepatide. Tirzepatide (brand names Mounjaro, Zepbound) is a double glucagon hormone receptor agonist (GLP-1 and GIP receptors), making it more effective for body fat mass reduction than its predecessor Semaglutide by targeting further receptors.",
    priceFrom: 13,
    variants: [{"id":"1v","name":"1x Vial","price":13,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":58.5,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":97.5,"savingsLabel":"Save £32.50"}],
    image: "https://growthguys.is/wp-content/uploads/Tirz-10-Red-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "tb-500-5mg",
    name: "TB-500 5mg",
    slug: "tb-500-5mg",
    tag: "PEPTIDE",
    description: "Each vial contains 5mg of highly pure TB-500. TB-500 (TB-4, short for Thymosin β4) is a naturally-occurring peptide that plays a vital role in the repair and regeneration of injured cells and tissues by promoting cell migration, forming new blood vessels and regenerating the tissue as well as decreasing the number of myofibroblasts in wounds, ...",
    priceFrom: 8.45,
    variants: [{"id":"1v","name":"1x Vial","price":8.45,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":35.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":63.375,"savingsLabel":"Save £21.13"}],
    image: "https://growthguys.is/wp-content/uploads/TB500-Purple-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "semaglutide-5mg",
    name: "Semaglutide 5mg",
    slug: "semaglutide-5mg",
    tag: "PEPTIDE",
    description: "Each vial contains 5mg of highly pure Semaglutide. Semaglutide (brand names Ozempic, Wegovy) is used for weight loss, to lower blood sugar levels, and to reduce the risk of major cardiovascular events such as heart attack or stroke in certain patients. It is a GLP-1 agonist to be administered subcutaneously once a week that works ...",
    priceFrom: 11.05,
    variants: [{"id":"1v","name":"1x Vial","price":11.05,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":48.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":82.875,"savingsLabel":"Save £27.63"}],
    image: "https://growthguys.is/wp-content/uploads/Sema-Blue-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "retatrutide-10mg",
    name: "Retatrutide 10mg",
    slug: "retatrutide-10mg",
    tag: "PEPTIDE",
    description: "Each vial contains 10mg of highly pure Retatrutide. Retatrutide is classified as a triple glucagon hormone receptor agonist (GLP-1, GIP, and GCGR receptors), making it more effective for body fat mass reduction than its predecessor Semaglutide by targeting further receptors.",
    priceFrom: 19.5,
    variants: [{"id":"1v","name":"1x Vial","price":19.5,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":91,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":146.25,"savingsLabel":"Save £48.75"}],
    image: "https://growthguys.is/wp-content/uploads/R10-Red-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "hcg-7-000iu",
    name: "hCG 7,000iu",
    slug: "hcg-7-000iu",
    tag: "PEPTIDE",
    description: "Each vial contains 7,000iu of highly pure Human Chorionic Gonadotropin (hCG). Human chorionic gonadotropin (HCG) is prescribed for men to address the symptoms of hypogonadism, such as low testosterone and infertility. When testosterone is introduced exogenously such as during TRT, HCG helps to maintain fertility, testicular and penis size, cognitive function, and libido.",
    priceFrom: 8.45,
    variants: [{"id":"1v","name":"1x Vial","price":8.45,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":35.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":63.375,"savingsLabel":"Save £21.13"}],
    image: "https://growthguys.is/wp-content/uploads/hCG-7000iu-Pink-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "bpc-157-5mg",
    name: "BPC-157 5mg",
    slug: "bpc-157-5mg",
    tag: "PEPTIDE",
    description: "Each vial contains 5mg of highly pure BPC-157. BPC-157, short for Body Protection Compound 157, is a chain of fifteen amino acids with various mechanisms of action, including activating cells involved in tissue repair, including muscles, tendons, ligaments and the gastrointestinal tract, stimulating the synthesis of growth factors, and inhibiting inflammation.",
    priceFrom: 8.45,
    variants: [{"id":"1v","name":"1x Vial","price":8.45,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":35.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":63.375,"savingsLabel":"Save £21.13"}],
    image: "https://growthguys.is/wp-content/uploads/BPC5-Green-1-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "hcg-14-000iu",
    name: "hCG 14,000iu",
    slug: "hcg-14-000iu",
    tag: "PEPTIDE",
    description: "Each vial contains 14,000iu of highly pure Human Chorionic Gonadotropin (hCG). Human chorionic gonadotropin (HCG) is prescribed for men to address the symptoms of hypogonadism, such as low testosterone and infertility. When testosterone is introduced exogenously such as during TRT, HCG helps to maintain fertility, testicular and penis size, cognitive function, and libido.",
    priceFrom: 15.6,
    variants: [{"id":"1v","name":"1x Vial","price":15.6,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":71.5,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":117,"savingsLabel":"Save £39.00"}],
    image: "https://growthguys.is/wp-content/uploads/hCG-14000iu-Light-Blue-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "bpc-157-10mg",
    name: "BPC-157 10mg",
    slug: "bpc-157-10mg",
    tag: "PEPTIDE",
    description: "Each vial contains 10mg of highly pure BPC-157. BPC-157, short for Body Protection Compound 157, is a chain of fifteen amino acids with various mechanisms of action, including activating cells involved in tissue repair, including muscles, tendons, ligaments and the gastrointestinal tract, stimulating the synthesis of growth factors, and inhibiting inflammation.",
    priceFrom: 15.6,
    variants: [{"id":"1v","name":"1x Vial","price":15.6,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":71.5,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":117,"savingsLabel":"Save £39.00"}],
    image: "https://growthguys.is/wp-content/uploads/BPC-157-10mg-purple-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "bpc-157-tb-500-8220-healing-blend-8221-6mg-6mg",
    name: "BPC-157 / TB-500 &#8220;Healing Blend&#8221; 6mg/6mg",
    slug: "bpc-157-tb-500-8220-healing-blend-8221-6mg-6mg",
    tag: "PEPTIDE",
    description: "Each vial contains 6mg of BPC-157 and 6mg of TB-500. Our “Healing Blend” combines BPC-157 and TB-500 (TB-4) at an ideal 1:1 ratio that takes advantage of their synergistic healing effects when used in conjunction. BPC-157, short for Body Protection Compound 157, is a chain of fifteen amino acids with various mechanisms of action, including ...",
    priceFrom: 15.6,
    variants: [{"id":"1v","name":"1x Vial","price":15.6,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":71.5,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":117,"savingsLabel":"Save £39.00"}],
    image: "https://growthguys.is/wp-content/uploads/Healing-6-6-White-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "tesamorelin-10mg",
    name: "Tesamorelin 10mg",
    slug: "tesamorelin-10mg",
    tag: "PEPTIDE",
    description: "Each vial contains 10mg of highly pure Tesamorelin. Tesamorelin is a synthetic peptide that acts as a growth hormone-releasing hormone (GHRH) analog. It is primarily used to reduce abdominal fat in HIV-infected patients with lipodystrophy, a condition characterized by abnormal fat distribution. By stimulating the release of growth hormone, tesamorelin helps improve body composition and ...",
    priceFrom: 19.5,
    variants: [{"id":"1v","name":"1x Vial","price":19.5,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":91,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":146.25,"savingsLabel":"Save £48.75"}],
    image: "https://growthguys.is/wp-content/uploads/Tesa-10-Purple-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "cagrilintide-10mg",
    name: "Cagrilintide 10mg",
    slug: "cagrilintide-10mg",
    tag: "PEPTIDE",
    description: "Each vial contains 10mg of highly pure Cagrilintide. Cagrilintide is a novel peptide developed as a treatment for obesity and weight management. It is a dual agonist that targets both the GLP-1 (glucagon-like peptide-1) and the amylin receptor, which helps to regulate appetite and glucose metabolism. By enhancing feelings of fullness and reducing hunger, cagrilintide ...",
    priceFrom: 22.1,
    variants: [{"id":"1v","name":"1x Vial","price":22.1,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":104,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":165.75,"savingsLabel":"Save £55.25"}],
    image: "https://growthguys.is/wp-content/uploads/Cagri-Red-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "survodutide-10mg",
    name: "Survodutide 10mg",
    slug: "survodutide-10mg",
    tag: "PEPTIDE",
    description: "Each vial contains 10mg of highly pure Survodutide. Survodutide is a peptide drug that acts as a dual agonist for GLP-1 (glucagon-like peptide-1) and GIP (gastric inhibitory polypeptide) receptors. It is being studied primarily for its potential in treating obesity and type 2 diabetes by helping to regulate appetite, enhance satiety, and improve glucose control. ...",
    priceFrom: 22.1,
    variants: [{"id":"1v","name":"1x Vial","price":22.1,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":104,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":165.75,"savingsLabel":"Save £55.25"}],
    image: "https://growthguys.is/wp-content/uploads/Survo-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "melanotan-2-10mg",
    name: "Melanotan-2 10mg",
    slug: "melanotan-2-10mg",
    tag: "PEPTIDE",
    description: "Each vial contains 10mg of highly pure Melanotan-2. Melanotan 2 is a synthetic analog of the naturally occurring melanocyte-stimulating hormone (MSH). It is primarily used to stimulate melanin production in the skin, leading to tanning without the need for sun exposure. Additionally, melanotan 2 has been studied for its potential effects on appetite suppression and ...",
    priceFrom: 8.45,
    variants: [{"id":"1v","name":"1x Vial","price":8.45,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":35.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":63.375,"savingsLabel":"Save £21.13"}],
    image: "https://growthguys.is/wp-content/uploads/MT-2-Yellow-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "igf-1-lr3-1mg",
    name: "IGF-1 LR3 1mg",
    slug: "igf-1-lr3-1mg",
    tag: "HGH",
    description: "IGF-1 LR3 (Insulin-like Growth Factor 1 Long Arg3) is a synthetic form of IGF-1, a protein that plays a key role in growth, development, and cellular repair. It's similar to the naturally occurring IGF-1 in your body but has a longer half-life due to a modification in its structure—specifically, the substitution of the active amino acids to increase biological activity.",
    priceFrom: 16.25,
    variants: [{"id":"1v","name":"1x Vial","price":16.25,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":74.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":121.875,"savingsLabel":"Save £40.63"}],
    image: "https://growthguys.is/wp-content/uploads/IGF-1-LR3-Orange-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "pt-141-10mg",
    name: "PT-141 10mg",
    slug: "pt-141-10mg",
    tag: "PEPTIDE",
    description: "PT-141 (Bremelanotide) is a peptide used to treat sexual dysfunction. FDA-approved as Vyleesi, it treats hypoactive sexual desire disorder (HSDD) in women and is also studied for erectile dysfunction (ED). Unlike Viagra, it works by stimulating the melanocortin system in the brain to enhance arousal. Administered via injection, effects start within 30-60 minutes and last ...",
    priceFrom: 11.05,
    variants: [{"id":"1v","name":"1x Vial","price":11.05,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":48.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":82.875,"savingsLabel":"Save £27.63"}],
    image: "https://growthguys.is/wp-content/uploads/PT-141-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "ipamorelin-10mg",
    name: "Ipamorelin 10mg",
    slug: "ipamorelin-10mg",
    tag: "PEPTIDE",
    description: "Ipamorelin is a growth hormone secretagogue (GHS) and selective ghrelin receptor agonist that stimulates the release of growth hormone (GH). It is often used for anti-aging, muscle growth, fat loss, and recovery. Key Benefits: Increases Growth Hormone naturally without raising cortisol or prolactin. Enhances Muscle Growth & Recovery by promoting protein synthesis. Supports Fat Loss ...",
    priceFrom: 15.6,
    variants: [{"id":"1v","name":"1x Vial","price":15.6,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":71.5,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":117,"savingsLabel":"Save £39.00"}],
    image: "https://growthguys.is/wp-content/uploads/Ipamorelin-10mg-Pink-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "epitalon-10mg",
    name: "Epitalon 10mg",
    slug: "epitalon-10mg",
    tag: "PEPTIDE",
    description: "Epitalon is a synthetic tetrapeptide (Ala-Glu-Asp-Gly) known for its potential anti-aging and telomere-lengthening effects. It was developed based on the natural epithalamin peptide produced in the pineal gland. Key Benefits: Promotes Longevity: May extend telomere length, slowing cellular aging. Enhances Sleep & Circadian Rhythms: Regulates melatonin production. Boosts Immune Function: Supports overall health and resilience. ...",
    priceFrom: 8.45,
    variants: [{"id":"1v","name":"1x Vial","price":8.45,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":35.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":63.375,"savingsLabel":"Save £21.13"}],
    image: "https://growthguys.is/wp-content/uploads/Epitalon-Orange-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "cjc-1295-with-dac-12-5mg",
    name: "CJC-1295 with DAC 12.5mg",
    slug: "cjc-1295-with-dac-12-5mg",
    tag: "PEPTIDE",
    description: "CJC-1295 with DAC is a synthetic growth hormone-releasing hormone (GHRH) analog that increases growth hormone (GH) and IGF-1 levels for muscle growth, fat loss, and anti-aging benefits. The DAC (Drug Affinity Complex) extends its half-life, allowing weekly dosing instead of frequent injections. Key Benefits: Increases Growth Hormone & IGF-1 for muscle growth and fat loss. ...",
    priceFrom: 22.1,
    variants: [{"id":"1v","name":"1x Vial","price":22.1,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":104,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":165.75,"savingsLabel":"Save £55.25"}],
    image: "https://growthguys.is/wp-content/uploads/CJC-DAC-GREY-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "glow-blend-50mg",
    name: "GLOW Blend 50mg",
    slug: "glow-blend-50mg",
    tag: "PEPTIDE",
    description: "The GLOW Protocol Peptide Blend is a synergistic combination of three peptides: GHK-Cu, TB-500, and BPC-157. This blend is designed to enhance regenerative processes and support systemic recovery. Components: GHK-Cu (Copper Peptide): A tripeptide that binds copper ions, known for its role in promoting collagen production and skin regeneration. TB-500 (Thymosin Beta-4 Fragment): A synthetic ...",
    priceFrom: 18.85,
    variants: [{"id":"1v","name":"1x Vial","price":18.85,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":87.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":141.375,"savingsLabel":"Save £47.13"}],
    image: "https://growthguys.is/wp-content/uploads/GLOW-White-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "cjc-1295-no-dac-ipamorelin-blend",
    name: "CJC-1295 no DAC + Ipamorelin Blend",
    slug: "cjc-1295-no-dac-ipamorelin-blend",
    tag: "PEPTIDE",
    description: "Each vial contains 5mg of EACH CJC-1295 no DAC + Ipamorelin in lyophilized form. CJC-1295 is a synthetic growth hormone-releasing hormone (GHRH) analog designed to increase growth hormone (GH) and IGF-1 levels for muscle growth, fat loss, anti-aging, and recovery. It stimulates the pituitary gland to produce GH, mimicking the body's natural process. CJC-1295 without ...",
    priceFrom: 16.25,
    variants: [{"id":"1v","name":"1x Vial","price":16.25,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":74.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":121.875,"savingsLabel":"Save £40.63"}],
    image: "https://growthguys.is/wp-content/uploads/CJC-IPA-Green-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "sermorelin-10mg",
    name: "Sermorelin 10mg",
    slug: "sermorelin-10mg",
    tag: "PEPTIDE",
    description: "Each vial contains 10mg of highly pure Sermorelin. Sermorelin is a synthetic peptide that stimulates the release of growth hormone (GH) from the pituitary gland. It is a growth hormone-releasing hormone (GHRH) analog, meaning it mimics the natural GHRH produced by the hypothalamus. Sermorelin itself does not contain growth hormone but encourages the body to ...",
    priceFrom: 16.25,
    variants: [{"id":"1v","name":"1x Vial","price":16.25,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":74.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":121.875,"savingsLabel":"Save £40.63"}],
    image: "https://growthguys.is/wp-content/uploads/Sermorelin-Green-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "tb-500-10mg",
    name: "TB-500 10mg",
    slug: "tb-500-10mg",
    tag: "PEPTIDE",
    description: "Each vial contains 10mg of highly pure TB-500. TB-500 (TB-4, short for Thymosin β4) is a naturally-occurring peptide that plays a vital role in the repair and regeneration of injured cells and tissues by promoting cell migration, forming new blood vessels and regenerating the tissue as well as decreasing the number of myofibroblasts in wounds, ...",
    priceFrom: 15.6,
    variants: [{"id":"1v","name":"1x Vial","price":15.6,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":71.5,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":117,"savingsLabel":"Save £39.00"}],
    image: "https://growthguys.is/wp-content/uploads/TB-500-10mg-Pink-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "ghk-cu-70mg",
    name: "GHK-Cu 70mg",
    slug: "ghk-cu-70mg",
    tag: "PEPTIDE",
    description: "GHK-Cu Copper Peptide – Skin Regeneration & Anti-Aging Powerhouse Rediscover youthful skin with GHK-Cu (Copper Tripeptide-1), a naturally occurring peptide renowned for its regenerative and anti-aging properties. This potent compound combines the tripeptide GHK (glycyl-L-histidyl-L-lysine) with a copper ion, creating a biologically active molecule that supports skin health, hair growth, and tissue repair. Key Benefits: ...",
    priceFrom: 8.45,
    variants: [{"id":"1v","name":"1x Vial","price":8.45,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":35.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":63.375,"savingsLabel":"Save £21.13"}],
    image: "https://growthguys.is/wp-content/uploads/GHK-Cu-70mg-Green-1024x928.jpg",
    thumbnails: []
  },
  {
    id: "mots-c-10mg",
    name: "MOTS-C 10mg",
    slug: "mots-c-10mg",
    tag: "PEPTIDE",
    description: "Each vial contains 10mg of highly pure MOTS-C. MOTS-c (Mitochondrial Open Reading Frame of the 12S rRNA Type-c) is a mitochondrial-derived peptide consisting of 16 amino acids. It plays a key role in cellular metabolism and energy homeostasis, acting through pathways related to insulin sensitivity, glucose metabolism, and stress response.",
    priceFrom: 8.45,
    variants: [{"id":"1v","name":"1x Vial","price":8.45,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":35.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":63.375,"savingsLabel":"Save £21.13"}],
    image: "https://growthguys.is/wp-content/uploads/MOTS-C-Pink-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "ss-31-50mg",
    name: "SS-31 50mg",
    slug: "ss-31-50mg",
    tag: "PEPTIDE",
    description: "Each vial contains 50mg of highly pure SS-31. SS-31 (also known as Elamipretide) is a synthetic tetrapeptide (D-Arg-Dmt-Lys-Phe-NH₂) known for its unique mitochondrial-targeting properties. SS-31 selectively binds to cardiolipin within the inner mitochondrial membrane, helping to stabilize mitochondrial structure and improve bioenergetics. Its antioxidant and cell-protective actions have made it a key molecule in mitochondrial ...",
    priceFrom: 32.5,
    variants: [{"id":"1v","name":"1x Vial","price":32.5,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":156,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":243.75,"savingsLabel":"Save £81.25"}],
    image: "https://growthguys.is/wp-content/uploads/SS-31-Green-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "semax-10mg",
    name: "Semax 10mg",
    slug: "semax-10mg",
    tag: "PEPTIDE",
    description: "Each vial contains 10mg of highly pure Semax in lyophilized form. Please note this batch is overdosed to ~13mg per vial, per the Janoshik test report. Semax is a synthetic peptide derived from the adrenocorticotropic hormone (ACTH) fragment (Met-Glu-His-Phe-Pro-Gly-Pro). Originally developed in Russia, Semax has been widely studied for its potential nootropic, neuroprotective, and neurorestorative properties. ...",
    priceFrom: 11.05,
    variants: [{"id":"1v","name":"1x Vial","price":11.05,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":48.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":82.875,"savingsLabel":"Save £27.63"}],
    image: "https://growthguys.is/wp-content/uploads/Semax-Grey-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "semaglutide-10mg",
    name: "Semaglutide 10mg",
    slug: "semaglutide-10mg",
    tag: "PEPTIDE",
    description: "Each vial contains 10mg of highly pure Semaglutide. Semaglutide (brand names Ozempic, Wegovy) is used for weight loss, to lower blood sugar levels, and to reduce the risk of major cardiovascular events such as heart attack or stroke in certain patients. It is a GLP-1 agonist to be administered subcutaneously once a week that works ...",
    priceFrom: 17.55,
    variants: [{"id":"1v","name":"1x Vial","price":17.55,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":81.25,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":131.625,"savingsLabel":"Save £43.88"}],
    image: "https://growthguys.is/wp-content/uploads/Sema-10-Blue-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "retatrutide-20mg",
    name: "Retatrutide 20mg",
    slug: "retatrutide-20mg",
    tag: "PEPTIDE",
    description: "Each vial contains 20mg of highly pure Retatrutide. Retatrutide is classified as a triple glucagon hormone receptor agonist (GLP-1, GIP, and GCGR receptors), making it more effective for body fat mass reduction than its predecessor Semaglutide by targeting further receptors.",
    priceFrom: 32.5,
    variants: [{"id":"1v","name":"1x Vial","price":32.5,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":156,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":243.75,"savingsLabel":"Save £81.25"}],
    image: "https://growthguys.is/wp-content/uploads/Reta-20-Purple-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "cjc-1295-no-dac-10mg",
    name: "CJC-1295 no DAC 10mg",
    slug: "cjc-1295-no-dac-10mg",
    tag: "PEPTIDE",
    description: "Each vial contains 10mg of highly pure CJC-1295 no DAC. Please note this batch is overdosed to closer to 12.5mg per vial per the Janoshik test report. OverviewCJC-1295 no DAC is a synthetic peptide belonging to the growth hormone–releasing hormone (GHRH) analog class. Unlike the DAC (Drug Affinity Complex) version, the no-DAC form has a shorter ...",
    priceFrom: 8.45,
    variants: [{"id":"1v","name":"1x Vial","price":8.45,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":35.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":63.375,"savingsLabel":"Save £21.13"}],
    image: "https://growthguys.is/wp-content/uploads/CJCNODAC10-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "mazdutide-10mg",
    name: "Mazdutide 10mg",
    slug: "mazdutide-10mg",
    tag: "PEPTIDE",
    description: "Each vial contains 10mg of highly pure Mazdutide. Mazdutide is a synthetic dual GLP-1/GIP receptor agonist studied for its role in metabolic regulation. Research has explored its effects on glucose control, insulin response, and body weight management in preclinical and clinical trials.",
    priceFrom: 22.1,
    variants: [{"id":"1v","name":"1x Vial","price":22.1,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":104,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":165.75,"savingsLabel":"Save £55.25"}],
    image: "https://growthguys.is/wp-content/uploads/Mazdutide-Red-color-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "thymosin-alpha-1-12-5mg",
    name: "Thymosin Alpha-1 12.5mg",
    slug: "thymosin-alpha-1-12-5mg",
    tag: "PEPTIDE",
    description: "Each vial contains 12.5mg of highly pure Thymosin Alpha-1. Thymosin Alpha-1 (Tα1) is a naturally occurring peptide fragment derived from thymosin fraction 5, originally isolated from the thymus gland. It has been widely studied for its potential role in modulating immune response and supporting immune system function in preclinical and clinical research settings.",
    priceFrom: 15.6,
    variants: [{"id":"1v","name":"1x Vial","price":15.6,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":71.5,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":117,"savingsLabel":"Save £39.00"}],
    image: "https://growthguys.is/wp-content/uploads/TA1-Grey-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "klow-blend-80mg",
    name: "KLOW Blend 80mg",
    slug: "klow-blend-80mg",
    tag: "PEPTIDE",
    description: "Each vial contains a blend of highly pure BPC-157, TB-500, KPV, and GHK-Cu. KLOW is a proprietary research blend combining four synergistic peptides—BPC-157, TB-500, KPV, and GHK-Cu—designed for advanced laboratory investigation into immune modulation, inflammation control, tissue repair, and cellular signaling. By combining these compounds, the KLOW blend offers researchers a unique opportunity to explore ...",
    priceFrom: 22.1,
    variants: [{"id":"1v","name":"1x Vial","price":22.1,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":104,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":165.75,"savingsLabel":"Save £55.25"}],
    image: "https://growthguys.is/wp-content/uploads/KLOW-Grey-1024x929.jpg",
    thumbnails: []
  },
  {
    id: "kpv-10mg",
    name: "KPV 10mg",
    slug: "kpv-10mg",
    tag: "PEPTIDE",
    description: "Each vial contains 10mg of highly pure KPV. KPV is a naturally occurring tripeptide fragment (Lysine-Proline-Valine) derived from the hormone alpha-MSH. It has been studied extensively in research for its anti-inflammatory, immune-modulating, and wound-healing potential. Because of its small size and stability, KPV has become a focus of laboratory investigation into novel therapeutic pathways for ...",
    priceFrom: 11.05,
    variants: [{"id":"1v","name":"1x Vial","price":11.05,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":48.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":82.875,"savingsLabel":"Save £27.63"}],
    image: "https://growthguys.is/wp-content/uploads/KPV-10-Blue-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "selank-12-5mg",
    name: "Selank 12.5mg",
    slug: "selank-12-5mg",
    tag: "PEPTIDE",
    description: "Each vial contains 12.5mg of highly pure lyophilized Selank. Selank is a synthetic peptide analog of the naturally occurring tuftsin fragment, designed for research into its potential neuromodulatory and anxiolytic effects. It has been investigated for its influence on mood regulation, cognitive function, and stress resilience.",
    priceFrom: 15.6,
    variants: [{"id":"1v","name":"1x Vial","price":15.6,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":71.5,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":117,"savingsLabel":"Save £39.00"}],
    image: "https://growthguys.is/wp-content/uploads/SELANK-Mockup-1024x929.jpg",
    thumbnails: []
  },
  {
    id: "glutathione-1500mg",
    name: "Glutathione 1500mg",
    slug: "glutathione-1500mg",
    tag: "PEPTIDE",
    description: "Overview Glutathione is a naturally occurring tripeptide composed of glutamine, cysteine, and glycine — often referred to as the body’s master antioxidant. It plays a central role in detoxification, immune defense, and cellular repair by neutralizing free radicals and reactive oxygen species. Mechanism of Action Injectable (parenteral) glutathione delivers the reduced form (GSH) directly into ...",
    priceFrom: 11.05,
    variants: [{"id":"1v","name":"1x Vial","price":11.05,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":48.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":82.875,"savingsLabel":"Save £27.63"}],
    image: "https://growthguys.is/wp-content/uploads/Glutathione-885x1024.jpg",
    thumbnails: []
  },
  {
    id: "retatrutide-60mg",
    name: "Retatrutide 60mg",
    slug: "retatrutide-60mg",
    tag: "PEPTIDE",
    description: "Important note: this is a standard peptide vial and will only hold a maximum of about 3.5mL of bacteriostatic water. Each vial contains 60mg of highly pure Retatrutide. Retatrutide is classified as a triple glucagon hormone receptor agonist (GLP-1, GIP, and GCGR receptors), making it more effective for body fat mass reduction than its predecessor ...",
    priceFrom: 65.65,
    variants: [{"id":"1v","name":"1x Vial","price":65.65,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":321.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":492.375,"savingsLabel":"Save £164.13"}],
    image: "https://growthguys.is/wp-content/uploads/Retatrutide-Mockup-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "l-carnitine-750mg-ml",
    name: "L-Carnitine 750mg/mL",
    slug: "l-carnitine-750mg-ml",
    tag: "PEPTIDE",
    description: "Each vial contains 30mL of L-Carnitine at 750mg/mL. L-Carnitine (Levocarnitine) is a naturally occurring quaternary ammonium compound involved in mitochondrial energy metabolism. In research settings, L-Carnitine plays a central role in the transport of long-chain fatty acids into the mitochondria, where they can be oxidized for ATP production. This mechanism makes it a valuable compound ...",
    priceFrom: 15.6,
    variants: [{"id":"1v","name":"1x Vial","price":15.6,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":71.5,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":117,"savingsLabel":"Save £39.00"}],
    image: "https://growthguys.is/wp-content/uploads/L-Carnitine-Mockup-944x1024.jpg",
    thumbnails: []
  },
  {
    id: "tirzepatide-30mg",
    name: "Tirzepatide 30mg",
    slug: "tirzepatide-30mg",
    tag: "PEPTIDE",
    description: "Each vial contains 30mg of highly pure Tirzepatide. Tirzepatide (brand names Mounjaro, Zepbound) is a double glucagon hormone receptor agonist (GLP-1 and GIP receptors), making it more effective for body fat mass reduction than its predecessor Semaglutide by targeting further receptors.",
    priceFrom: 32.5,
    variants: [{"id":"1v","name":"1x Vial","price":32.5,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":156,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":243.75,"savingsLabel":"Save £81.25"}],
    image: "https://growthguys.is/wp-content/uploads/T30-Black-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "nad-350mg",
    name: "NAD+ 350mg",
    slug: "nad-350mg",
    tag: "PEPTIDE",
    description: "Each 10mL vial contains 350mg of lyophilized NAD+. Overview:High-purity NAD+ (Nicotinamide Adenine Dinucleotide) solution used in research on cellular energy, mitochondrial function, metabolic pathways, and stress responses. Potential Benefits (Research Context Only):Studies suggest NAD+ may: Support cellular energy production (ATP generation) Influence mitochondrial health and biogenesis Play a role in DNA repair pathways Affect cellular ...",
    priceFrom: 6.5,
    variants: [{"id":"1v","name":"1x Vial","price":6.5,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":26,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":48.75,"savingsLabel":"Save £16.25"}],
    image: "https://growthguys.is/wp-content/uploads/L-2-1-1024x1024.jpg",
    thumbnails: []
  },
  {
    id: "ll-37-10mg",
    name: "LL-37 10mg",
    slug: "ll-37-10mg",
    tag: "PEPTIDE",
    description: "Each vial contains 10mg of highly pure LL-37 in lyophilized form. LL-37 is a synthetic version of the human cathelicidin antimicrobial peptide, produced to high purity for laboratory and research applications. Known for its role in innate immune signaling and host-defense mechanisms, LL-37 is widely studied for its interactions with microbial membranes, immune modulation pathways, and ...",
    priceFrom: 11.05,
    variants: [{"id":"1v","name":"1x Vial","price":11.05,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":48.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":82.875,"savingsLabel":"Save £27.63"}],
    image: "https://growthguys.is/wp-content/uploads/LL-37-White-1024x929.jpg",
    thumbnails: []
  },
  {
    id: "dsip-12-5mg",
    name: "DSIP 12.5mg",
    slug: "dsip-12-5mg",
    tag: "PEPTIDE",
    description: "Each vial contains 12.5mg of highly pure DSIP in lyophilized form. DSIP (Delta Sleep-Inducing Peptide) Injectable is a synthetic peptide corresponding to the naturally occurring neuropeptide studied for its role in neuroendocrine regulation and circadian biology. DSIP is commonly used in research exploring sleep-related signaling pathways, stress responses, and peptide–receptor interactions within the central nervous ...",
    priceFrom: 11.05,
    variants: [{"id":"1v","name":"1x Vial","price":11.05,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":48.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":82.875,"savingsLabel":"Save £27.63"}],
    image: "https://growthguys.is/wp-content/uploads/DSIP-12.5-Red-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "kisspeptin-12-5mg",
    name: "Kisspeptin 12.5mg",
    slug: "kisspeptin-12-5mg",
    tag: "PEPTIDE",
    description: "Each vial contains 12.5mg of highly pure Kisspeptin in lyophilized form. Kisspeptin Peptide is a synthetic form of the naturally occurring neuropeptide widely studied for its role in neuroendocrine signaling and reproductive axis regulation. It is commonly used in research investigating hypothalamic signaling pathways, hormone release mechanisms, and peptide–receptor interactions. Manufactured to high purity and ...",
    priceFrom: 11.05,
    variants: [{"id":"1v","name":"1x Vial","price":11.05,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":48.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":82.875,"savingsLabel":"Save £27.63"}],
    image: "https://growthguys.is/wp-content/uploads/Kisspeptin-12.5mg-Purple-1024x929.jpg",
    thumbnails: []
  },
  {
    id: "5-amino-1mq-10mg",
    name: "5-Amino-1MQ 10mg",
    slug: "5-amino-1mq-10mg",
    tag: "PEPTIDE",
    description: "Each vial contains 10mg of highly pure 5-Amino-1MQ in lyophilized form. Please note it is normal that this product is orange, not white like a typical lyophilized peptide. 5-Amino-1MQ is commonly discussed for its potential effects on metabolic pathways, particularly through inhibition of NNMT. Reported or explored effects include improved regulation of energy metabolism, reduced ...",
    priceFrom: 8.45,
    variants: [{"id":"1v","name":"1x Vial","price":8.45,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":35.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":63.375,"savingsLabel":"Save £21.13"}],
    image: "https://growthguys.is/wp-content/uploads/5-Amino-Yellow-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "human-menopausal-gonadotropin-hmg-75iu-8211-hmg01",
    name: "Human Menopausal Gonadotropin (HMG) 75iu &#8211; HMG01",
    slug: "human-menopausal-gonadotropin-hmg-75iu-8211-hmg01",
    tag: "PEPTIDE",
    description: "Each vial contains 75iu of highly pure Human Menopausal Gonadotropin (HMG). Human Menopausal Gonadotropin (hMG) is a purified gonadotropin preparation containing follicle-stimulating hormone (FSH) and luteinizing hormone (LH). It is commonly prescribed by fertility specialists as part of medically supervised treatment protocols for reproductive health. hMG is derived from human sources and formulated for injection. ...",
    priceFrom: 11.05,
    variants: [{"id":"1v","name":"1x Vial","price":11.05,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":48.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":82.875,"savingsLabel":"Save £27.63"}],
    image: "https://growthguys.is/wp-content/uploads/5-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "tesamorelin-20mg",
    name: "Tesamorelin 20mg",
    slug: "tesamorelin-20mg",
    tag: "PEPTIDE",
    description: "Each vial contains 20mg of highly pure Tesamorelin. Tesamorelin is a synthetic peptide that acts as a growth hormone-releasing hormone (GHRH) analog. It is primarily used to reduce abdominal fat in HIV-infected patients with lipodystrophy, a condition characterized by abnormal fat distribution. By stimulating the release of growth hormone, tesamorelin helps improve body composition and ...",
    priceFrom: 32.5,
    variants: [{"id":"1v","name":"1x Vial","price":32.5,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":156,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":243.75,"savingsLabel":"Save £81.25"}],
    image: "https://growthguys.is/wp-content/uploads/6-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "bpc-157-tb-500-healing-blend-10mg-10mg",
    name: "BPC-157 / TB-500 “Healing Blend” 10mg/10mg",
    slug: "bpc-157-tb-500-healing-blend-10mg-10mg",
    tag: "PEPTIDE",
    description: "Each vial contains 10mg of BPC-157 and 10mg of TB-500. Our “Healing Blend” combines BPC-157 and TB-500 (TB-4) at an ideal 1:1 ratio that takes advantage of their synergistic healing effects when used in conjunction. BPC-157, short for Body Protection Compound 157, is a chain of fifteen amino acids with various mechanisms of action, including ...",
    priceFrom: 17.55,
    variants: [{"id":"1v","name":"1x Vial","price":17.55,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":81.25,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":131.625,"savingsLabel":"Save £43.88"}],
    image: "https://growthguys.is/wp-content/uploads/3-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "mots-c-40mg",
    name: "MOTS-C 40mg",
    slug: "mots-c-40mg",
    tag: "PEPTIDE",
    description: "Each vial contains 40mg of highly pure MOTS-C. MOTS-c (Mitochondrial Open Reading Frame of the 12S rRNA Type-c) is a mitochondrial-derived peptide consisting of 16 amino acids. It plays a key role in cellular metabolism and energy homeostasis, acting through pathways related to insulin sensitivity, glucose metabolism, and stress response.",
    priceFrom: 26,
    variants: [{"id":"1v","name":"1x Vial","price":26,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":123.5,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":195,"savingsLabel":"Save £65.00"}],
    image: "https://growthguys.is/wp-content/uploads/7-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "cerebrolysin-6-x-60mg-360mg-box",
    name: "Cerebrolysin 6 x 60mg (360mg Box)",
    slug: "cerebrolysin-6-x-60mg-360mg-box",
    tag: "PEPTIDE",
    description: "Cerebrolysin is a sterile injectable preparation derived from purified porcine brain extracts. It contains a balanced mixture of amino acids and small peptides designed to support metabolic activity of nerve cells. This product is clinically used as an adjunct therapy for patients with cognitive impairment caused by traumatic brain injury or cerebrovascular diseases. It may ...",
    priceFrom: 27.3,
    variants: [{"id":"1v","name":"1x Vial","price":27.3,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":130,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":204.75,"savingsLabel":"Save £68.25"}],
    image: "https://growthguys.is/wp-content/uploads/Cerebrolysin-Box-1024x618.jpg",
    thumbnails: []
  },
  {
    id: "bpc-157-arginate-tablets",
    name: "BPC-157 Arginate Tablets",
    slug: "bpc-157-arginate-tablets",
    tag: "PEPTIDE",
    description: "Each order of AndroNorth BPC-157 Arginate Tablets contains one (1) satchet of sixty (60) tablets, each containing 500 micrograms of highly pure BPC-157 Arginate. BPC-157 Arginate is a synthetic peptide derived from a naturally occurring compound found in gastric juice, known as Body Protection Compound-157 (BPC-157). It has gained attention for its potential role in ...",
    priceFrom: 32.5,
    variants: [{"id":"1v","name":"1x Vial","price":32.5,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":156,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":243.75,"savingsLabel":"Save £81.25"}],
    image: "https://growthguys.is/wp-content/uploads/BPC-157-Arginate-1024x1024.jpg",
    thumbnails: []
  },
  {
    id: "melanotan-1-10mg",
    name: "Melanotan-1 10mg",
    slug: "melanotan-1-10mg",
    tag: "PEPTIDE",
    description: "Each vial contains 10mg of highly pure Melanotan-1 in lyophilized form. Melanotan-1 is a synthetic peptide formulated to support the body’s natural pigmentation processes. Designed for subcutaneous administration under professional supervision, it is intended for use in controlled settings where modulation of melanin production is desired. Manufactured to high purity standards, it offers consistent quality ...",
    priceFrom: 11.05,
    variants: [{"id":"1v","name":"1x Vial","price":11.05,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":48.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":82.875,"savingsLabel":"Save £27.63"}],
    image: "https://growthguys.is/wp-content/uploads/11-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "brain-blend-6mg-6mg",
    name: "Brain Blend 6mg/6mg",
    slug: "brain-blend-6mg-6mg",
    tag: "PEPTIDE",
    description: "Each vial of Brain Blend contains 6mg of each Semax and Selank in highly pure, lyophilized form. Brain Blend (Semax + Selank) is a synergistic peptide formulation designed to support cognitive clarity, balanced mood, and overall mental performance. Combining the complementary properties of Semax and Selank, this advanced blend is developed for subcutaneous administration under professional ...",
    priceFrom: 13,
    variants: [{"id":"1v","name":"1x Vial","price":13,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":58.5,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":97.5,"savingsLabel":"Save £32.50"}],
    image: "https://growthguys.is/wp-content/uploads/4-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "chonluten-30mg",
    name: "Chonluten 30mg",
    slug: "chonluten-30mg",
    tag: "PEPTIDE",
    description: "Each vial contains 30mg of highly pure Chonluten in lyophilized form. Chonluten is a synthetic peptide formulation developed to support cellular health and tissue function. Designed for use in controlled settings under professional supervision, it is manufactured to high purity standards to ensure consistent quality and reliability. Chonluten is intended for specialized research and performance-focused ...",
    priceFrom: 11.05,
    variants: [{"id":"1v","name":"1x Vial","price":11.05,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":48.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":82.875,"savingsLabel":"Save £27.63"}],
    image: "https://growthguys.is/wp-content/uploads/8-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "cardiogen-20mg",
    name: "Cardiogen 20mg",
    slug: "cardiogen-20mg",
    tag: "PEPTIDE",
    description: "Each vial contains 20mg of highly pure Cardiogen in lyophilized form. Cardiogen is a peptide-based formulation developed to support cardiovascular cellular function and overall tissue vitality. Designed for administration under professional supervision, it is manufactured to high purity standards to ensure consistency and quality. Injectable Cardiogen is intended for specialized research and performance-focused applications where ...",
    priceFrom: 11.05,
    variants: [{"id":"1v","name":"1x Vial","price":11.05,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":48.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":82.875,"savingsLabel":"Save £27.63"}],
    image: "https://growthguys.is/wp-content/uploads/9-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "ovagen-10mg",
    name: "Ovagen 10mg",
    slug: "ovagen-10mg",
    tag: "PEPTIDE",
    description: "Each vial contains 10mg of highly pure Ovagen in lyophilized form. Ovagen is a peptide-based formulation developed to support cellular function and tissue balance. Designed for administration under professional supervision, it is manufactured to high purity standards to ensure consistency and reliability. Injectable Ovagen is intended for specialized research and performance-focused applications where targeted peptide ...",
    priceFrom: 8.45,
    variants: [{"id":"1v","name":"1x Vial","price":8.45,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":35.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":63.375,"savingsLabel":"Save £21.13"}],
    image: "https://growthguys.is/wp-content/uploads/2-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "thymulin-15mg",
    name: "Thymulin 15mg",
    slug: "thymulin-15mg",
    tag: "PEPTIDE",
    description: "Each vial contains 15mg of highly pure Thymulin in lyophilized form. Thymulin is a peptide-based formulation developed to support immune system modulation and cellular signaling processes. Designed for administration under professional supervision, it is manufactured to high purity standards to ensure consistency and quality. Injectable Thymulin is intended for specialized research and performance-focused applications where ...",
    priceFrom: 11.05,
    variants: [{"id":"1v","name":"1x Vial","price":11.05,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":48.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":82.875,"savingsLabel":"Save £27.63"}],
    image: "https://growthguys.is/wp-content/uploads/10-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "tirzepatide-60mg",
    name: "Tirzepatide 60mg",
    slug: "tirzepatide-60mg",
    tag: "PEPTIDE",
    description: "Each vial contains 60mg of highly pure Tirzepatide. Tirzepatide (brand names Mounjaro, Zepbound) is a double glucagon hormone receptor agonist (GLP-1 and GIP receptors), making it more effective for body fat mass reduction than its predecessor Semaglutide by targeting further receptors.",
    priceFrom: 49.4,
    variants: [{"id":"1v","name":"1x Vial","price":49.4,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":240.5,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":370.5,"savingsLabel":"Save £123.50"}],
    image: "https://growthguys.is/wp-content/uploads/Tirz-60-Blue-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "aod-9604-2-5mg",
    name: "AOD-9604 2.5mg",
    slug: "aod-9604-2-5mg",
    tag: "PEPTIDE",
    description: "Each vial contains 2.5mg of highly pure AOD-9604. AOD-9604 is a synthetic peptide fragment derived from the C-terminal region of human growth hormone (hGH), specifically engineered to isolate and study the lipolytic (fat-metabolizing) properties of hGH without its broader anabolic or growth-promoting effects. It is commonly investigated for its role in regulating fat metabolism, lipid ...",
    priceFrom: 8.45,
    variants: [{"id":"1v","name":"1x Vial","price":8.45,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":35.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":63.375,"savingsLabel":"Save £21.13"}],
    image: "https://growthguys.is/wp-content/uploads/AOD-Purple-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "ara-290-10mg",
    name: "ARA-290 10mg",
    slug: "ara-290-10mg",
    tag: "PEPTIDE",
    description: "Each vial contains 10mg of highly pure ARA-290. ARA-290 is a synthetic peptide derived from the tertiary structure of erythropoietin (EPO), specifically engineered to retain its tissue-protective and anti-inflammatory properties while avoiding the erythropoietic (red blood cell–stimulating) effects associated with full-length EPO. It is primarily studied for its role in modulating innate repair pathways, reducing ...",
    priceFrom: 11.05,
    variants: [{"id":"1v","name":"1x Vial","price":11.05,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":48.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":82.875,"savingsLabel":"Save £27.63"}],
    image: "https://growthguys.is/wp-content/uploads/ARA-290-Purple-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "pinealon-10mg",
    name: "Pinealon 10mg",
    slug: "pinealon-10mg",
    tag: "PEPTIDE",
    description: "Each vial contains 10mg of highly pure Pinealon. Pinealon is a synthetic short peptide composed of three amino acids (Glu-Asp-Arg), developed as part of a class of regulatory peptides studied for their potential effects on neuronal function, gene expression, and cellular aging processes. It is primarily investigated for its role in supporting cognitive function, neuroprotection, ...",
    priceFrom: 11.05,
    variants: [{"id":"1v","name":"1x Vial","price":11.05,"savingsLabel":""},{"id":"5v","name":"5x Vials","price":48.75,"savingsLabel":"Save £10"},{"id":"10v","name":"10x Vials","price":82.875,"savingsLabel":"Save £27.63"}],
    image: "https://growthguys.is/wp-content/uploads/Pinnealon-Purple-1024x930.jpg",
    thumbnails: []
  },
  {
    id: "bacteriostatic-water-pfizer",
    name: "Bacteriostatic Water (Pfizer)",
    slug: "bacteriostatic-water-pfizer",
    tag: "ANCILLARY",
    description: "PLEASE NOTE: Due to nationwide shortages, customers may receive U.S. Hospira branded Bacteriostatic Water in substitution. Identical product produced by the same company (Hospira owned by Pfizer) branded differently in U.S./Canada.\n\nThis listing contains 1 bottle (30mL) of Pfizer or Hospira Bacteriostatic Water for reconstitution of lyophilized peptides and HGH.\n\nBacteriostatic Water for Injection, USP is a sterile, nonpyrogenic preparation of water for injection containing 0.9% (9 mg/mL) of benzyl alcohol added as a preservative. It is supplied in a multiple-dose container from which repeated withdrawals may be made to dilute or dissolve drugs for injection.",
    priceFrom: 13,
    variants: [{"id":"1b","name":"1x 30mL Bottle","price":13,"savingsLabel":""},{"id":"5b","name":"5x 30mL Bottles","price":58.5,"savingsLabel":"Save £10"}],
    image: "https://growthguys.is/wp-content/uploads/Mockup-12-scaled.jpg",
    thumbnails: []
  },
  {
    id: "hgh-batch-ggc32-110iu-kit",
    name: "HGH – Batch GGC32 110iu Kit",
    slug: "hgh-batch-ggc32-110iu-kit",
    tag: "HGH",
    description: "Batch GGC32 Human Growth Hormone (191AA HGH) Kit contains 10 vials of high-quality Somatropin. Independent 3rd-party laboratory testing verifies an outstanding purity of 97.27% with an average mass of 11.03 iu per vial (110iu total kit). Widely researched for its role in cellular repair, fat loss, muscle regeneration, and anti-aging applications. Manufactured under strict guidelines to ensure maximum stability and biopotency.",
    priceFrom: 107.25,
    variants: [{"id":"1k","name":"1x Kit (110iu)","price":107.25,"savingsLabel":""}],
    image: "https://growthguys.is/wp-content/uploads/HGH-Kit-White@0.5x-600x600.webp",
    thumbnails: []
  },
  {
    id: "hgh-batch-ggc36-420iu-kit",
    name: "HGH – Batch GGC36 420iu Kit",
    slug: "hgh-batch-ggc36-420iu-kit",
    tag: "HGH",
    description: "Batch GGC36 Human Growth Hormone (191AA HGH) Kit represents our premium high-dose Somatropin offering. This kit contains 10 vials, each verified by independent 3rd-party HPLC testing to contain a purity of 97.85% and an average active mass of 42.72 iu of premium HGH per vial (over 420iu total per kit). Perfect for advanced research requirements focusing on tissue growth, metabolic rate enhancement, muscular hypertrophy, and accelerated physical recovery.",
    priceFrom: 273,
    variants: [{"id":"1k","name":"1x Kit (420iu)","price":273,"savingsLabel":""}],
    image: "https://growthguys.is/wp-content/uploads/HGH-Kit-Purple@0.5x-600x600.webp",
    thumbnails: []
  },
  {
    id: "cloudtropin-batch-ggc34-430iu-kit",
    name: "“Cloudtropin” Batch GGC34 430iu Kit",
    slug: "cloudtropin-batch-ggc34-430iu-kit",
    tag: "HGH",
    description: "“Cloudtropin” Batch GGC34 (191AA HGH) is a specialized, budget-friendly high-dose Somatropin kit containing 10 vials (43iu per vial, 430iu total). This batch of HGH is manufactured using pharmaceutical-grade API and excipients, but due to an exceptionally high concentration, it remains slightly cloudy/foggy upon reconstitution. This 'Fog Factor' does not affect its verified 96.65% purity or active potency. Offering maximum performance and biopotency at an incredible value.",
    priceFrom: 195,
    variants: [{"id":"1k","name":"1x Kit (430iu)","price":195,"savingsLabel":""}],
    image: "https://growthguys.is/wp-content/uploads/Cloudtropin-Transparent-Background-600x600.png",
    thumbnails: []
  },
];

export const faqs = [
  { q: "What is your shipping policy?", a: "We ship Australia-wide via Express Post. Orders placed before 2PM AEST are dispatched the same day." },
  { q: "Are these products for human consumption?", a: "Yes, these products are for human consumption." },
  { q: "How should peptides be stored?", a: "Store lyophilized powder in the freezer at -20°C for long-term stability. Once reconstituted, peptides must be refrigerated at 2-8°C and used within an appropriate timeframe." },
  { q: "Do you provide Certificates of Analysis?", a: "Yes, every batch we offer undergoes rigorous third-party testing. COAs for our products are readily available on their respective product pages." },
  { q: "What payment methods do you accept?", a: "We accept secure payments and provide invoice details upon order confirmation via our WhatsApp/Email ordering system." }
];

export const blogPosts = [
  {
    slug: 'where-to-buy-retatrutide-australia',
    image: 'https://peptidelabuk.co.uk/wp-content/uploads/2026/04/68c153351d1a646053b66e98_Retatrutide-5MG-With-Pen-1-scaled.jpg',
    title: 'Where to buy Retatrutide in Australia',
    date: '2026-07-01',
    author: 'Research Team',
    excerpt: 'A comprehensive guide on sourcing high-purity research peptides locally in Australia, avoiding scams, and ensuring quality.',
    content: '## Sourcing High-Purity Peptides\nFinding a reliable supplier for research peptides like Retatrutide in Australia requires careful consideration of purity, third-party testing, and local shipping logistics. Many overseas suppliers face customs delays, making local sourcing the most efficient choice for domestic laboratories.\n\n### Why Third-Party Testing Matters\nAlways insist on a Certificate of Analysis (COA) from an independent lab. This ensures the peptide sequence is correct and free from synthesis impurities.'
  },
  {
    slug: 'peptide-reconstitution-guide',
    image: 'https://growthguys.is/wp-content/uploads/Tirz-10-Red-1024x930.jpg',
    title: 'Peptide Reconstitution Guide for Australian Labs',
    date: '2026-06-15',
    author: 'Lab Tech',
    excerpt: 'Best practices for reconstituting lyophilized peptides safely and effectively for research purposes.',
    content: '## Best Practices for Reconstitution\nProper handling of lyophilized peptides is crucial to maintain their structural integrity. Always use bacteriostatic water or sterile saline depending on your research protocol.\n\n### Step-by-Step Guide\n1. Allow the vial to reach room temperature.\n2. Swab the stopper with alcohol.\n3. Slowly inject the diluent, letting it run down the side of the glass.\n4. Do not shake. Swirl gently until completely dissolved.'
  }
];
